/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FYP;

import javax.swing.JFrame;

/**
 *
 * @author Mohammad Ahsan
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public RegistrationForm() {
        initComponents();
        this.setSize(756, 660);
        password.setEchoChar('\u2022');
        validName.setPreferredSize(new java.awt.Dimension(73, 14));
        validFatherName.setPreferredSize(new java.awt.Dimension(120, 14));
        validDOB.setPreferredSize(new java.awt.Dimension(130, 14));
        validDOJ.setPreferredSize(new java.awt.Dimension(130, 14));
        validID.setPreferredSize(new java.awt.Dimension(130, 14));
        validQualification.setPreferredSize(new java.awt.Dimension(110, 14));
        validContactNum.setPreferredSize(new java.awt.Dimension(113, 14));
        validEmail.setPreferredSize(new java.awt.Dimension(90, 14));
        validPassword.setPreferredSize(new java.awt.Dimension(100, 14));
        validName.setText("");
        validFatherName.setText("");
        validDOB.setText("");
        validDOJ.setText("");
        validID.setText("");
        validQualification.setText("");
        validContactNum.setText("");
        validEmail.setText("");
        validPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        fatherName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        validFatherName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        birthDate = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        validDOB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        joiningDate = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        validDOJ = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminID = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        validID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qualification = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        validQualification = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contactNum = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        validContactNum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        validEmail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jSeparator9 = new javax.swing.JSeparator();
        validPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        validName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));
        jPanel2.setPreferredSize(new java.awt.Dimension(340, 141));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel10.setBackground(new java.awt.Color(74, 31, 61));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FYP/Globe.png"))); // NOI18N
        jPanel2.add(jLabel10, new java.awt.GridBagConstraints());

        jLabel11.setBackground(new java.awt.Color(186, 79, 84));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(186, 79, 84));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("F Y P    M A N A G E M E N T");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(35, 0, 0, 0);
        jPanel2.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(186, 79, 84));
        jLabel12.setText("S Y S T E M");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel2.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(360, 141));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 141));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(186, 79, 84));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Your Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(46, 40, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        name.setBackground(new java.awt.Color(186, 79, 84));
        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(46, 8, 0, 0);
        jPanel3.add(name, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator1, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(186, 79, 84));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Father Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        fatherName.setBackground(new java.awt.Color(186, 79, 84));
        fatherName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fatherName.setForeground(new java.awt.Color(255, 255, 255));
        fatherName.setBorder(null);
        fatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherNameKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 8, 0, 0);
        jPanel3.add(fatherName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator2, gridBagConstraints);

        validFatherName.setForeground(new java.awt.Color(255, 255, 255));
        validFatherName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validFatherName.setText("Invalid Father Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 27);
        jPanel3.add(validFatherName, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(186, 79, 84));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date of Birth:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        birthDate.setBackground(new java.awt.Color(186, 79, 84));
        birthDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        birthDate.setForeground(new java.awt.Color(255, 255, 255));
        birthDate.setBorder(null);
        birthDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                birthDateKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel3.add(birthDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator3, gridBagConstraints);

        validDOB.setBackground(new java.awt.Color(186, 79, 84));
        validDOB.setForeground(new java.awt.Color(255, 255, 255));
        validDOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validDOB.setText("Invalid Date of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 27);
        jPanel3.add(validDOB, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(186, 79, 84));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date of Joining:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        joiningDate.setBackground(new java.awt.Color(186, 79, 84));
        joiningDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        joiningDate.setForeground(new java.awt.Color(255, 255, 255));
        joiningDate.setBorder(null);
        joiningDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                joiningDateKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel3.add(joiningDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator4, gridBagConstraints);

        validDOJ.setBackground(new java.awt.Color(186, 79, 84));
        validDOJ.setForeground(new java.awt.Color(255, 255, 255));
        validDOJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validDOJ.setText("Invalid Date of Joining");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 20);
        jPanel3.add(validDOJ, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(186, 79, 84));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Administrator ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        adminID.setBackground(new java.awt.Color(186, 79, 84));
        adminID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminID.setForeground(new java.awt.Color(255, 255, 255));
        adminID.setBorder(null);
        adminID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminIDKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel3.add(adminID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator5, gridBagConstraints);

        validID.setBackground(new java.awt.Color(186, 79, 84));
        validID.setForeground(new java.awt.Color(255, 255, 255));
        validID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validID.setText("Invalid Administrator ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 10);
        jPanel3.add(validID, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(186, 79, 84));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Qualifcation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        qualification.setBackground(new java.awt.Color(186, 79, 84));
        qualification.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qualification.setForeground(new java.awt.Color(255, 255, 255));
        qualification.setBorder(null);
        qualification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qualificationKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 0);
        jPanel3.add(qualification, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator6, gridBagConstraints);

        validQualification.setBackground(new java.awt.Color(186, 79, 84));
        validQualification.setForeground(new java.awt.Color(255, 255, 255));
        validQualification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validQualification.setText("Invalid Qualification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 30);
        jPanel3.add(validQualification, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(186, 79, 84));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contact Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        contactNum.setBackground(new java.awt.Color(186, 79, 84));
        contactNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactNum.setForeground(new java.awt.Color(255, 255, 255));
        contactNum.setBorder(null);
        contactNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNumKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel3.add(contactNum, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator7, gridBagConstraints);

        validContactNum.setBackground(new java.awt.Color(186, 79, 84));
        validContactNum.setForeground(new java.awt.Color(255, 255, 255));
        validContactNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validContactNum.setText("Invalid Contact Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        jPanel3.add(validContactNum, gridBagConstraints);

        jLabel8.setBackground(new java.awt.Color(186, 79, 84));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Email ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.insets = new java.awt.Insets(10, 60, 0, 0);
        jPanel3.add(jLabel8, gridBagConstraints);

        email.setBackground(new java.awt.Color(186, 79, 84));
        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel3.add(email, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator8, gridBagConstraints);

        validEmail.setBackground(new java.awt.Color(186, 79, 84));
        validEmail.setForeground(new java.awt.Color(255, 255, 255));
        validEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validEmail.setText("Invalid Email ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 40);
        jPanel3.add(validEmail, gridBagConstraints);

        jLabel9.setBackground(new java.awt.Color(186, 79, 84));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 31;
        gridBagConstraints.insets = new java.awt.Insets(10, 55, 0, 0);
        jPanel3.add(jLabel9, gridBagConstraints);

        password.setBackground(new java.awt.Color(186, 79, 84));
        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("00000000");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 31;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        jPanel3.add(password, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 0);
        jPanel3.add(jSeparator9, gridBagConstraints);

        validPassword.setBackground(new java.awt.Color(186, 79, 84));
        validPassword.setForeground(new java.awt.Color(255, 255, 255));
        validPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validPassword.setText("Invalid Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 33;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 30);
        jPanel3.add(validPassword, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(186, 79, 84));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(186, 79, 84));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 35;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jButton2, gridBagConstraints);

        validName.setBackground(new java.awt.Color(186, 79, 84));
        validName.setForeground(new java.awt.Color(255, 255, 255));
        validName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validName.setText("Invalid Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 57);
        jPanel3.add(validName, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Create An Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel3.add(jLabel13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanel3, gridBagConstraints);

        setSize(new java.awt.Dimension(756, 660));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        if(name.getText().equals("Aho")) {
            validName.setText("Invalid Name");
        }
        else {
            validName.setText("");
        }
    }//GEN-LAST:event_nameKeyReleased

    private void fatherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherNameKeyReleased
        // TODO add your handling code here:
        if(fatherName.getText().equals("Ij")) {
            validFatherName.setText("Invalid Father Name");
        }
        else {
            validFatherName.setText("");
        }
    }//GEN-LAST:event_fatherNameKeyReleased

    private void birthDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthDateKeyReleased
        // TODO add your handling code here:
        if(birthDate.getText().equals("123")) {
            validDOB.setText("Invalid Date of Birth");
        }
        else {
            validDOB.setText("");
        }
    }//GEN-LAST:event_birthDateKeyReleased

    private void joiningDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_joiningDateKeyReleased
        // TODO add your handling code here:
        if(joiningDate.getText().equals("123")) {
            validDOJ.setText("Invalid Date of Joining");
        }
        else {
            validDOJ.setText("");
        }
    }//GEN-LAST:event_joiningDateKeyReleased

    private void adminIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminIDKeyReleased
        // TODO add your handling code here:
        if(adminID.getText().equals("123")) {
            validID.setText("Invalid Administrator ID");
        }
        else {
            validID.setText("");
        }
    }//GEN-LAST:event_adminIDKeyReleased

    private void qualificationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qualificationKeyReleased
        // TODO add your handling code here:
        if(qualification.getText().equals("qwe")) {
            validQualification.setText("Invalid Qualification");
        }
        else {
            validQualification.setText("");
        }
    }//GEN-LAST:event_qualificationKeyReleased

    private void contactNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumKeyReleased
        // TODO add your handling code here:
        if(contactNum.getText().equals("123")) {
            validContactNum.setText("Invalid Contact Number");
        }
        else {
            validContactNum.setText("");
        }
    }//GEN-LAST:event_contactNumKeyReleased

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        if(email.getText().equals("123")) {
            validEmail.setText("Invalid Email ID");
        }
        else {
            validEmail.setText("");
        }
    }//GEN-LAST:event_emailKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        
        if(password.getText().equals("123")) {
            validPassword.setText("Invalid Password");
        }
        else {
            validPassword.setText("");
        }
    }//GEN-LAST:event_passwordKeyReleased

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(password.getText().equals("00000000")) {
            password.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminID;
    private javax.swing.JTextField birthDate;
    private javax.swing.JTextField contactNum;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fatherName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField joiningDate;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField qualification;
    private javax.swing.JLabel validContactNum;
    private javax.swing.JLabel validDOB;
    private javax.swing.JLabel validDOJ;
    private javax.swing.JLabel validEmail;
    private javax.swing.JLabel validFatherName;
    private javax.swing.JLabel validID;
    private javax.swing.JLabel validName;
    private javax.swing.JLabel validPassword;
    private javax.swing.JLabel validQualification;
    // End of variables declaration//GEN-END:variables
}
